# ============================================================
# AI PIPELINE FOR:
# Visualizing Machine Learning Model Evaluation Metrics
#
# INPUT:
#   - model_evaluation_metrics.csv (from 03Train_Multiple_Models.py)
#
# OUTPUT:
#   - model_comparison_plots.png
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# STEP 1: LOAD METRICS DATA
# ============================================================
print("\nLoading model evaluation metrics...")
try:
    df = pd.read_csv("model_evaluation_metrics.csv")
except FileNotFoundError:
    print("Error: 'model_evaluation_metrics.csv' not found. Please run 03Train_Multiple_Models.py first.")
    exit()

# ============================================================
# STEP 2: SETUP PLOTS
# ============================================================

# Metrics generated by the previous step
metrics_to_plot = ["Accuracy", "Weighted_F1", "ROC_AUC", "MCC", "Cohen_Kappa", "Log_Loss"]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

print("Generating visualizations...")

# ============================================================
# STEP 3: PLOT EACH METRIC
# ============================================================
for i, metric in enumerate(metrics_to_plot):
    # Determine sorting order (Log_Loss is 'lower is better', so ascending=True)
    ascending = True if metric == "Log_Loss" else False
    
    # Sort data for this specific subplot to show the best models at the top
    sorted_df = df.sort_values(by=metric, ascending=ascending)
    
    sns.barplot(
        data=sorted_df,
        x=metric,
        y="Model",
        ax=axes[i],
        palette="viridis"
    )
    
    axes[i].set_title(f'Model Comparison: {metric}', fontsize=14, pad=10)
    axes[i].set_xlabel(metric, fontsize=12)
    axes[i].set_ylabel('') # Remove y-axis label to keep it clean
    
    # Add values at the end of the bars for exact readings
    for container in axes[i].containers:
        axes[i].bar_label(container, fmt='%.4f', padding=3)

plt.tight_layout()
output_filename = "model_comparison_plots.png"
plt.savefig(output_filename, dpi=300, bbox_inches='tight')
plt.close()

print(f"Metrics visualizations saved successfully to {output_filename}!")